#!/bin/sh
# Only host orchestration and read-only network inspection; Python runs in Docker.
set -eu
cd "$(dirname "$0")/.."
compose() { docker compose -f deploy/dev/compose.yaml -f deploy/dev/compose.live.yaml "$@"; }
bootstrap() {
    # Hard-coded sandbox for checking even a malicious Compose before starting it.
    docker run --rm -i --network none --cap-drop ALL --security-opt no-new-privileges --read-only --tmpfs /tmp -v "$PWD:/workspace:ro" -w /workspace awg-dev-tooling:local "$@"
}
lint() { compose --profile '*' config --format json | bootstrap python scripts/check_network_safety.py "$PWD"; }
build() {
    docker build -f deploy/dev/Dockerfile.tooling -t awg-dev-tooling:local .
    docker build -f deploy/dev/Dockerfile.services -t awg-dev-services:local .
    docker build -f apps/node-agent/Dockerfile -t awg-dev-agent:local .
    docker build -f deploy/dev/Dockerfile.live -t awg-dev-live:local .
}
finish() {
    status=$?
    trap - EXIT INT TERM
    scripts/host-snapshot.sh "$evidence/host-after" || status=1
    bootstrap python scripts/compare_host.py "$evidence/host-before" "$evidence/host-after" || status=1
    rmdir artifacts/lab.lock || status=1
    exit "$status"
}
phase() {
    echo "=== E2E phase: $1"
    compose run --rm -T -e "E2E_PHASE=$1" tooling pytest -p no:cacheprovider -q -m network tests/e2e
}
stock_setup() {
    compose --profile stock up -d --wait remnawave stock-proxy
    compose run --rm -T pki-init
    compose run --rm -T stock-bootstrap
}
e2e() {
    scripts/live-preflight.sh
    stock_setup
    compose --profile extension --profile live up -d --wait --force-recreate controller gateway awg-agent awg-client target
    phase connect
    phase lifecycle
    compose stop controller
    phase controller_down
    compose up -d --wait controller
    compose restart awg-agent
    phase agent_restart
    compose restart controller
    compose up -d --wait controller
    phase controller_restart
    # Removal: extension fully stopped, subscriptions go straight to stock.
    compose stop gateway controller awg-agent
    phase removed
    tables=$(compose exec -T remnawave-db psql -U remnawave -d remnawave -Atc \
        "SELECT count(*) FROM information_schema.tables WHERE table_name ILIKE 'awg%'")
    [ "$tables" = 0 ] || { echo "Stock DB contains extension tables: $tables" >&2; exit 1; }
    echo 'Stock DB has no extension tables: PASS'
    compose --profile extension --profile live up -d --wait controller gateway awg-agent
    phase restored
    phase delete
    echo 'E2E: PASS'
}
cmd=${1:-help}
[ "$#" -gt 0 ] && shift
case $cmd in
    build) build ;;
    credentials)
        # Lab-only admin generated by bootstrap; stored in a named volume, never in the workspace.
        docker run --rm --network none -v awg-dev_lab-credentials:/c:ro awg-dev-tooling:local \
            python -c "import json; a=json.load(open('/c/stock-admin.json')); print('Remnawave login:', a['username'], '/', a['password'])"
        ;;
    lint) lint ;;
    live-preflight) scripts/live-preflight.sh ;;
    tui)
        tty=; [ -t 0 ] || tty=-T
        compose --profile extension run --rm $tty tui python -m awg_tui "$@" ;;
    test|up-stock|down|setup|up-extension|panel|e2e|installer)
        action=$cmd
        lint
        mkdir -p artifacts
        mkdir artifacts/lab.lock || { echo 'Another lab operation is active; refuse concurrent snapshots' >&2; exit 1; }
        evidence=artifacts/run-$(date +%Y%m%dT%H%M%S)-$$
        scripts/host-snapshot.sh "$evidence/host-before"
        trap finish EXIT INT TERM
        compose --profile '*' config --format json | bootstrap python scripts/check_pool_overlap.py "$evidence/host-before"
        case "$action" in
            test)
                compose up -d --wait awg-db
                if [ "$#" -eq 0 ]; then set -- tests; fi
                compose run --rm -T tooling pytest -p no:cacheprovider "$@"
                ;;
            up-stock) compose --profile stock up -d --wait remnawave ;;
            setup) stock_setup ;;
            up-extension) compose --profile extension up -d --wait controller gateway ;;
            panel)
                stock_setup
                compose --profile stock --profile extension --profile live up -d --wait controller gateway panel subscription-page awg-agent awg-client target
                echo 'Remnawave panel: https://127.0.0.1:18443  (self-signed lab certificate)'
                echo 'Subscription page: https://127.0.0.1:18444/<shortUuid>'
                echo 'AWG terminal UI: scripts/lab.sh tui'
                echo 'Login:           scripts/lab.sh credentials'
                ;;
            e2e) e2e 2>&1 | tee "$evidence/e2e.log"; [ "$(tail -1 "$evidence/e2e.log")" = 'E2E: PASS' ] ;;
            installer)
                stock_setup
                scripts/test-installer.sh 2>&1 | tee "$evidence/installer.log"
                tail -1 "$evidence/installer.log" | grep -q 'INSTALLER: PASS'
                ;;
            down) compose --profile '*' down ;;
        esac
        ;;
    *) echo 'Usage: scripts/lab.sh build|lint|test [pytest args]|setup|up-stock|up-extension|panel|credentials|tui [status|peers]|e2e|installer|down|live-preflight'; exit 2 ;;
esac
